<a href="https://colab.research.google.com/github/pramodhhbk/PyTorch-Playground/blob/main/PyTorch_WB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TENSORS**

In [1]:
## A torch.Tensor is a multi-dimensional matrix containing elements of single data type.
## Default data type is float32
## More suitable for DL than a numpy array

In [3]:
### LISTS

my_list = [[1,2,3,4],[5,6,7,8]]
my_list

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [4]:
### Numpy Array
import numpy as np

np1 = np.random.rand(3,4)
np1

array([[0.33682218, 0.85084841, 0.97983154, 0.04316205],
       [0.20438103, 0.01588793, 0.64966754, 0.9162728 ],
       [0.34068917, 0.54912575, 0.44650442, 0.28750965]])

In [5]:
np1.dtype

dtype('float64')

In [6]:
## Tensors

import torch

tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.9586, -0.0165, -0.5962, -0.7192],
        [ 0.8595, -0.9460, -0.8527,  0.1722],
        [-0.7855, -0.0531, -1.3384, -2.6137]])

In [7]:
tensor_3d = torch.zeros(3,3)
tensor_3d

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [8]:
### Create tensor out of np array

my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.3368, 0.8508, 0.9798, 0.0432],
        [0.2044, 0.0159, 0.6497, 0.9163],
        [0.3407, 0.5491, 0.4465, 0.2875]], dtype=torch.float64)